# fly.toml app configuration file generated for birdtrip-zmcda on 2026-07-14T02:17:49Z
#
# See https://fly.io/docs/reference/configuration/ for information about how to use this file.
#

app = 'birdtrip-zmcda'
primary_region = 'ewr'

[build]

[env]
  BIRDTRIP_DB = '/data/birdtrip.sqlite'
  BIRDTRIP_DUCK_MEM = '3GB'
  BIRDTRIP_DUCK_THREADS = '2'
  BIRDTRIP_DUCK_TMP = '/data/duckdb_tmp'
  PORT = '8080'

[[mounts]]
  source = 'birdtrip_data'
  destination = '/data'

[http_service]
  internal_port = 8080
  force_https = true
  auto_stop_machines = 'off'
  min_machines_running = 1

  [http_service.concurrency]
    type = 'requests'
    hard_limit = 16
    soft_limit = 8

  [[http_service.checks]]
    interval = '30s'
    timeout = '5s'
    grace_period = '2m0s'
    method = 'GET'
    path = '/healthz'

[[vm]]
  size = 'shared-cpu-2x'
  memory = '4096mb'
